apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: tailscale-operator
    meta.helm.sh/release-namespace: tailscale
  creationTimestamp: "2025-11-01T05:13:36Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: operator
  namespace: tailscale
  resourceVersion: "214493"
  uid: e63d70e2-3510-425c-ad62-2ba77b3e2f84
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: OPERATOR_INITIAL_TAGS
          value: tag:k8s-operator
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_LOGIN_SERVER
        - name: OPERATOR_INGRESS_CLASS_NAME
          value: tailscale
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_IMAGE
          value: tailscale/tailscale:v1.90.6
        - name: PROXY_TAGS
          value: tag:k8s
        - name: APISERVER_PROXY
          value: "false"
        - name: PROXY_FIREWALL_MODE
          value: auto
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: tailscale/k8s-operator:v1.90.6
        imagePullPolicy: Always
        name: operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: operator
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: oauth
        secret:
          defaultMode: 420
          secretName: operator-oauth
status:
  conditions:
  - lastTransitionTime: "2025-11-01T05:13:36Z"
    lastUpdateTime: "2025-11-01T05:13:36Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-11-01T05:13:36Z"
    lastUpdateTime: "2025-11-01T05:13:36Z"
    message: ReplicaSet "operator-5876f76c44" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
