apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: docker.io/jakecahill/be-app
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: backend
      app.kubernetes.io/part-of: three-tier