apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-here-change-in-production"
  DB_USERNAME: "iec"
  DB_PASSWORD: "123456789@"
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"
