apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: apps
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3456
      targetPort: 3456
  type: LoadBalancer
  loadBalancerClass: tailscale
